# Appveyor config for CodeReady Containers windows tray
---
image: Visual Studio 2019

configuration: Release

before_build:
  ps: nuget restore crc-tray.sln

build:
  project: crc-tray.sln

artifacts:
  - path: bin\Release\crc-tray.exe
    type: File
    name: crc-tray
