# Appveyor config for CodeReady Containers windows tray
---
image: Visual Studio 2019

configuration: Release

before_build:
  ps: nuget restore tray-windows.sln

build:
  project: tray-windows.sln

after_build:
  ps: ls bin\

artifacts:
  - path: bin\Release
    name: crc-tray
